version: '2.1'
services:
  mongodb:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    command: mongod --noauth --smallfiles
    networks: 
      - webappnetwork
  app:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks: 
      - webappnetwork
networks: 
  webappnetwork:
    driver: bridge